name: Running Boards
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2084069720003754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3c2df'
    - '#060604'
    - '#ffffff'
    - '#db2136'
    - '#80736d'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
